// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.domain;

import edu.vanderbilt.drumbeat.domain.Image;
import edu.vanderbilt.drumbeat.domain.ImageDataOnDemand;
import edu.vanderbilt.drumbeat.domain.ImageIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ImageIntegrationTest: @Transactional;
    
    @Autowired
    private ImageDataOnDemand ImageIntegrationTest.dod;
    
    @Test
    public void ImageIntegrationTest.testCountImages() {
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = Image.countImages();
        Assert.assertTrue("Counter for 'Image' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImageIntegrationTest.testFindImage() {
        Image obj = dod.getRandomImage();
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = Image.findImage(id);
        Assert.assertNotNull("Find method for 'Image' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Image' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImageIntegrationTest.testFindAllImages() {
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = Image.countImages();
        Assert.assertTrue("Too expensive to perform a find all test for 'Image', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Image> result = Image.findAllImages();
        Assert.assertNotNull("Find all method for 'Image' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Image' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImageIntegrationTest.testFindImageEntries() {
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = Image.countImages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Image> result = Image.findImageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Image' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Image' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImageIntegrationTest.testFlush() {
        Image obj = dod.getRandomImage();
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = Image.findImage(id);
        Assert.assertNotNull("Find method for 'Image' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImage(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Image' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageIntegrationTest.testMergeUpdate() {
        Image obj = dod.getRandomImage();
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = Image.findImage(id);
        boolean modified =  dod.modifyImage(obj);
        Integer currentVersion = obj.getVersion();
        Image merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Image' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        Image obj = dod.getNewTransientImage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Image' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Image' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Image' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImageIntegrationTest.testRemove() {
        Image obj = dod.getRandomImage();
        Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = Image.findImage(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Image' with identifier '" + id + "'", Image.findImage(id));
    }
    
}
