// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.domain;

import edu.vanderbilt.drumbeat.domain.Image;
import edu.vanderbilt.drumbeat.domain.ImageDataOnDemand;
import edu.vanderbilt.drumbeat.domain.PersonDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ImageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ImageDataOnDemand: @Component;
    
    private Random ImageDataOnDemand.rnd = new SecureRandom();
    
    private List<Image> ImageDataOnDemand.data;
    
    @Autowired
    private PersonDataOnDemand ImageDataOnDemand.personDataOnDemand;
    
    public Image ImageDataOnDemand.getNewTransientImage(int index) {
        Image obj = new Image();
        setPathurl(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void ImageDataOnDemand.setPathurl(Image obj, int index) {
        String pathurl = "pathurl_" + index;
        obj.setPathurl(pathurl);
    }
    
    public void ImageDataOnDemand.setTitle(Image obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Image ImageDataOnDemand.getSpecificImage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Image obj = data.get(index);
        Long id = obj.getId();
        return Image.findImage(id);
    }
    
    public Image ImageDataOnDemand.getRandomImage() {
        init();
        Image obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Image.findImage(id);
    }
    
    public boolean ImageDataOnDemand.modifyImage(Image obj) {
        return false;
    }
    
    public void ImageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Image.findImageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Image' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Image>();
        for (int i = 0; i < 10; i++) {
            Image obj = getNewTransientImage(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
