// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.domain;

import edu.vanderbilt.drumbeat.domain.AudioDataOnDemand;
import edu.vanderbilt.drumbeat.domain.PersonDataOnDemand;
import edu.vanderbilt.drumbeat.domain.Video;
import edu.vanderbilt.drumbeat.domain.VideoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VideoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VideoDataOnDemand: @Component;
    
    private Random VideoDataOnDemand.rnd = new SecureRandom();
    
    private List<Video> VideoDataOnDemand.data;
    
    @Autowired
    private AudioDataOnDemand VideoDataOnDemand.audioDataOnDemand;
    
    @Autowired
    private PersonDataOnDemand VideoDataOnDemand.personDataOnDemand;
    
    public Video VideoDataOnDemand.getNewTransientVideo(int index) {
        Video obj = new Video();
        setPathurl(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void VideoDataOnDemand.setPathurl(Video obj, int index) {
        String pathurl = "pathurl_" + index;
        obj.setPathurl(pathurl);
    }
    
    public void VideoDataOnDemand.setTitle(Video obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Video VideoDataOnDemand.getSpecificVideo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Video obj = data.get(index);
        Long id = obj.getId();
        return Video.findVideo(id);
    }
    
    public Video VideoDataOnDemand.getRandomVideo() {
        init();
        Video obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Video.findVideo(id);
    }
    
    public boolean VideoDataOnDemand.modifyVideo(Video obj) {
        return false;
    }
    
    public void VideoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Video.findVideoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Video' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Video>();
        for (int i = 0; i < 10; i++) {
            Video obj = getNewTransientVideo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
