// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.domain;

import edu.vanderbilt.drumbeat.domain.Video;
import edu.vanderbilt.drumbeat.domain.VideoDataOnDemand;
import edu.vanderbilt.drumbeat.domain.VideoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VideoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VideoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VideoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VideoIntegrationTest: @Transactional;
    
    @Autowired
    private VideoDataOnDemand VideoIntegrationTest.dod;
    
    @Test
    public void VideoIntegrationTest.testCountVideos() {
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = Video.countVideos();
        Assert.assertTrue("Counter for 'Video' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VideoIntegrationTest.testFindVideo() {
        Video obj = dod.getRandomVideo();
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = Video.findVideo(id);
        Assert.assertNotNull("Find method for 'Video' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Video' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VideoIntegrationTest.testFindAllVideos() {
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = Video.countVideos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Video', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Video> result = Video.findAllVideos();
        Assert.assertNotNull("Find all method for 'Video' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Video' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VideoIntegrationTest.testFindVideoEntries() {
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = Video.countVideos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Video> result = Video.findVideoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Video' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Video' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VideoIntegrationTest.testFlush() {
        Video obj = dod.getRandomVideo();
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = Video.findVideo(id);
        Assert.assertNotNull("Find method for 'Video' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVideo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Video' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoIntegrationTest.testMergeUpdate() {
        Video obj = dod.getRandomVideo();
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = Video.findVideo(id);
        boolean modified =  dod.modifyVideo(obj);
        Integer currentVersion = obj.getVersion();
        Video merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Video' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        Video obj = dod.getNewTransientVideo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Video' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Video' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Video' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VideoIntegrationTest.testRemove() {
        Video obj = dod.getRandomVideo();
        Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = Video.findVideo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Video' with identifier '" + id + "'", Video.findVideo(id));
    }
    
}
