// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.algo;

import edu.vanderbilt.drumbeat.algo.CooleyTukeyFFT_Preprocessor;
import java.io.Serializable;

privileged aspect CooleyTukeyFFT_Preprocessor_Roo_Serializable {
    
    declare parents: CooleyTukeyFFT_Preprocessor implements Serializable;
    
}
