// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.algo;

import edu.vanderbilt.drumbeat.algo.CountingFilter;
import java.io.Serializable;

privileged aspect CountingFilter_Roo_Serializable {
    
    declare parents: CountingFilter implements Serializable;
    
}
