// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.algo;

import edu.vanderbilt.drumbeat.algo.RaderFFT_Preprocessor;
import java.io.Serializable;

privileged aspect RaderFFT_Preprocessor_Roo_Serializable {
    
    declare parents: RaderFFT_Preprocessor implements Serializable;
    
}
