// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.ui;

import edu.vanderbilt.drumbeat.ui.CompositeDataVisualizer;
import java.io.Serializable;

privileged aspect CompositeDataVisualizer_Roo_Serializable {
    
    declare parents: CompositeDataVisualizer implements Serializable;
    
}
