// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.ui;

import edu.vanderbilt.drumbeat.ui.LineDrawer;
import java.io.Serializable;

privileged aspect LineDrawer_Roo_Serializable {
    
    declare parents: LineDrawer implements Serializable;
    
}
