// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.ui;

import edu.vanderbilt.drumbeat.ui.TransposableDataVisualizer;
import java.io.Serializable;

privileged aspect TransposableDataVisualizer_Roo_Serializable {
    
    declare parents: TransposableDataVisualizer implements Serializable;
    
}
