// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.io;

import edu.vanderbilt.drumbeat.io.Wav_Reader;
import java.io.Serializable;

privileged aspect Wav_Reader_Roo_Serializable {
    
    declare parents: Wav_Reader implements Serializable;
    
}
