// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.vanderbilt.drumbeat.domain;

import edu.vanderbilt.drumbeat.domain.Image;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Image_Roo_Configurable {
    
    declare @type: Image: @Configurable;
    
}
